services:
  postgresql:
    image: postgres:16.4
    container_name: postgresql_app
    environment:
      POSTGRES_USER: golang_user
      POSTGRES_PASSWORD: StrongPass123!
      POSTGRES_DB: golang_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
